node {
    stage('CloneRepo') { 
        git 'https://github.com/Niardan/DevOps.git'
    }
    stage('Run') {
                  sh "mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < B11Workshop/B11.5/rfam.sql"
    }
}
