Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "file", source: "empty_file", destination: "empty_file"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y python3  python3-pip python-psycopg2 python3-django
  SHELL
end
